ginder/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'welcome/index'
  
  resources :profiles do
    resources :comments
  end
  
  resources :users do
    resources :profiles
  end
  
  get "profiles/index" => "profiles#index"
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ginder/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ginder/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :profile
end

ginder/app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :name, presence: true, length: { minimum: 2}
    validates :biography, presence: true
    
    def self.search(search)
        if search
            @profiles = Profile.find(:all, :conditions => ['name LIKE ?', "%#{params[:search]}%"])
        else
            @profiles = Profile.all
        end
    end
    
end

ginder/app/models/user.rb
class User < ApplicationRecord
    has_one :profile
    
    VALID_EMAIL_REGEX = /A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    before_save { self.email = email.downcase }
    
    validates :name,
        presence: true,
        length: { maximum: 12 }
    
    validates :email,
        presence: true,
        length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }
        
    validates :password,
        presence: true,
        length: { minimum: 6 }
        
    has_secure_password
end

ginder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
      if session[:user_id]
          @current_user ||= User.find(session[:user_id])
      else
          @current_user = nil
      end
  end
end

ginder/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @profile = Profile.find(params[:profile_id])
        @comment = @profile.comments.create(comment_params)
        redirect_to profile_path(@profile)
    end
    
    def destroy
        @profile = Profile.find(params[:profile_id])
        @comment = @profile.comments.find(params[:id])
        @comment.destroy
        redirect_to profile_path(@profile)
    end
    
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

ginder/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    def new
        @profile = Profile.new
    end
    
    def index
        if params[:search]
            @profiles = Profile.where(casual_or_competitive: params[:search])
        else
            @profiles = Profile.all
        end
    end
    
    def edit
        @profile = Profile.find(params[:id])
    end
    
    def update
        @profile = Profile.find(params[:id])
        if @profile.update(profile_params)
            redirect_to @profile
        else
            render 'edit'
        end
    end
    
    def profile_params
        params.require(:profile).permit(:name, :profile_id, :search)
    end
    
    def create
        @profile = Profile.new(profile_params)
        @profile.user = current_user
        if @profile.save
            redirect_to @profile
        else
            render 'new'
        end
    end
    
    def destroy
        @profile = Profile.find(params[:id])
        @profile.destroy
        redirect_to profiles_path
    end
    
    def show
        @profile = Profile.find(params[:id])
    end
    
    private
        def profile_params
            params.require(:profile).permit(:name, :biography, :favorite_game, :casual_or_competitive)
        end
    
end

ginder/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

ginder/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

ginder/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

ginder/app/helpers/application_helper.rb
module ApplicationHelper
end

ginder/app/helpers/comments_helper.rb
module CommentsHelper
end

ginder/app/helpers/profiles_helper.rb
module ProfilesHelper
end

ginder/app/helpers/sessions_helper.rb
module SessionsHelper
end

ginder/app/helpers/users_helper.rb
module UsersHelper
end

ginder/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ginder/app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
</p>

<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>

<p>
    <%= link_to 'Destroy Comment', [comment.profile, comment],
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
</p>

ginder/app/views/comments/_form.html.erb
<%= form_for([@profile, @profile.comments.build]) do |f| %>
<p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
</p>
<p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

ginder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ginder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ginder/app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
 
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@profile.errors.count, "error") %> prohibited
        this profile from being saved:
      </h2>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :biography %><br>
    <%= f.text_area :biography %>
  </p>
  
  <p>
    <%= f.label :favorite_game %><br>
    <%= f.text_field :favorite_game %>
  </p>
  
  <p>
    <%= f.label :casual_or_competitive %><br>
    <%= f.text_field :casual_or_competitive %>
  </p>  
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

ginder/app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>
 
<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

ginder/app/views/profiles/index.html.erb
<h1>Listing Profiles</h1>

<%= form_tag profiles_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag("Search", :name => nil) %>
<% end %>

<%= link_to 'New Profile', new_profile_path %>
 
<table>
  <tr>
    <th>Name</th>
    <th>Username</th>
    <th>Bio</th>
    <th>Favorite Game</th>
    <th>Casual / Competitive</th>
  </tr>
 
  <% @profiles.each do |profile| %>
    <tr>
      <td><%= profile.name %></td>
      <td>
        <% if profile.user %>
          <%= profile.user.name %>
        <% end %>
      </td>
      <td><%= profile.biography %></td>
      <td><%= profile.favorite_game %></td>
      <td><%= profile.casual_or_competitive %></td>
      <td><%= link_to 'Show', profile_path(profile) %></td>
      <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
      <td><%= link_to 'Destroy', profile_path(profile), method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

ginder/app/views/profiles/new.html.erb
<p>New Profile</p>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

ginder/app/views/profiles/show.html.erb
<p>
    <strong>Name:</strong>
    <%= @profile.name %>
    
    <strong>Bio:</strong>
    <%= @profile.biography %>
    
    <strong>Favorite Game:</strong>
    <%= @profile.favorite_game %>
    
    <strong>Casual / Competitive:</strong>
    <%= @profile.casual_or_competitive %>
</p>

<h2>Comments</h2>
<%= render @profile.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Profile List', profiles_path %>

ginder/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ginder/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

ginder/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

ginder/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

ginder/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

ginder/app/views/welcome/index.html.erb
<center><img src="https://cdn.discordapp.com/attachments/689668367761539113/701848933957108274/readyup.png" height="400" width="400" alt="Ready Up Logo"></center>
<br>
<center><p>
    <%= link_to 'Profiles', controller: 'profiles' %>
    
    <% if current_user %>
        Logged in as <%= current_user.name %>
        <%= link_to "Log Out", logout_path %>
    <% else %>
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
    <% end %>
    
</p></center>